apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus-deploy
  namespace: prometheus
spec:
  strategy: #Setando estratégia de atualização (rollingUpdate)
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  replicas: 2
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: bitnami/prometheus
        name: prometheus
        resources:
          requests:
            cpu: "250m"
            memory: "206Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
          - name: prometheus-config
            mountPath: /etc/prometheus

      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
