apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: blackbox-exporter
  namespace: exporters
spec:
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels: 
        app: blackbox-exporter
    spec:
      containers:
      - name: blackbox-exporter
        image: bitnami/blackbox-exporter
        ports:
        - containerPort: 9115
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: exporters
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels: 
        app: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: bitnami/node-exporter
        ports:
        - containerPort: 9100