apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-nginx
  name: nginx-deploy
  namespace: app-monitoring
spec:
  strategy: #Setando estratégia de atualização
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  replicas: 2
  selector:
    matchLabels:
      app: app-nginx
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
      - image: nginx
        name: app-nginx
        resources:
          requests:
            cpu: "250m"
            memory: "206Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"