apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db-postgres
  name: postgres-deploy
  namespace: database
spec:
  strategy: #Setando estratégia de atualização
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  replicas: 2
  selector:
    matchLabels:
      app: db-postgres
  template:
    metadata:
      labels:
        app: db-postgres
    spec:
      containers:
      - image: postgres:18
        name: db-postgres
        resources:
          requests:
            cpu: "250m"
            memory: "206Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env: #Setando variáveis de ambiente
        - name: POSTGRES_DB 
          valueFrom:
            configMapKeyRef:
              name: database-configmap
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: database-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: database-secret
              key: POSTGRES_PASSWORD