apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: database
spec:
  selector:
    app: db-postgres
  ports:
  - name: postgres-service
    port: 5432
    targetPort: 5432
  type: ClusterIP