apiVersion: v1
kind: Service
metadata:
  name: adminer-service
  namespace: database
spec:
  selector:
    app: db-adminer
  ports:
  - name: adminer-service
    port: 8080
    targetPort: 8080
    nodePort: 30000
  type: NodePort