apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db-adminer
  name: adminer-deploy
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-adminer
  template:
    metadata:
      labels:
        app: db-adminer
    spec:
      containers:
      - image: adminer:5.4.0
        name: db-adminer
        resources:
          requests:
            cpu: "250m"
            memory: "206Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 8080 #Porta que o adminer vai escutar